### ISSUE TITLE
Update env variable regex to support --arg=val and support commands

### ISSUE THREAD

**Issue by dretsa** [asika32764/php-cross-env#5]
The library works quite well, thank you for taking your time to write it!

 I wanted to use it for running my coverage tests with the required environment variable `XDEBUG_MODE=coverage` as I'm not sure what environment my co-workers will be running them in.

My composer json:
```json
{
    "scripts": {
        ...
        "coverage": "cross-env XDEBUG_MODE=coverage pest --coverage",
        "coverage:ci": "cross-env XDEBUG_MODE=coverage pest --colors=never --coverage --min=90",
        ...
    }
}
```

However, I faced two main issues with the current regex:
- The regex captures --arg=val arguments as environment variables ([example](https://regex101.com/r/sY2aqT/1))
- Setting env variable without quotemarks results in capturing everything until line end ([example](https://regex101.com/r/I9MueZ/1))

Another suggestion for improvement is to only allow `A-Za-z\d_` as environment variable names, as the allowed characters should be an intersect between the [allowed in Linux](https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names) and the [allowed in Windows](https://stackoverflow.com/questions/20635695/what-are-valid-characters-for-windows-environment-variable-names-and-values).

Current regex: `/(\w+)=(\'(.*)\'|"(.*)"|(.*))/`
Proposed regex: `\s([A-Za-z\d_]+)=(\'(.*)\'|"(.*)"|([^ ]*))`

I would be more than happy to open a PR to replace the regex :)

**Comment by dretsa** [comment]
On a side-note, there are two more things:
- When there are two or more commands, that have quotemarks, they all match as a single environment value ([example](https://regex101.com/r/jvsO95/1)). Making the regex lazy would fix that.
- Escaping of quotemarks should probably be possible (Not sure about that one yet, open to ideas)

**Comment by asika32764** [comment]
It's weird that I never meet the case that capturing everything until line end 

```
cross-env COMPOSER_TIMEOUT=600 composer install
```

But new regex seems more makes sense, could you please open a PR to fix it?

**Comment by asika32764** [comment]
I can't pass test with `\s([A-Za-z\d_]+)=(\'(.*)\'|"(.*)"|([^ ]*))`

But `\s*([A-Za-z\d_]+)=(\'(.*)\'|"(.*)"|([^ ]*))` works.

The 2.0 have already released, please try it, if there has any issues about new regex, please open a new PR.
